diff --git a/changelogs/fragments/162_import_error.yml b/changelogs/fragments/162_import_error.yml
new file mode 100644
index 0000000000..780ef976a8
--- /dev/null
+++ b/changelogs/fragments/162_import_error.yml
@@ -0,0 +1,3 @@
+---
+bugfixes:
+- common - import k8sdynamicclient directly to workaround Ansible upstream bug (https://github.com/ansible-collections/kubernetes.core/issues/162).
diff --git a/plugins/module_utils/common.py b/plugins/module_utils/common.py
index 48e55ec044..844d20aeba 100644
--- a/plugins/module_utils/common.py
+++ b/plugins/module_utils/common.py
@@ -53,7 +53,7 @@
 
 IMP_K8S_CLIENT = None
 try:
-    from ansible_collections.kubernetes.core.plugins.module_utils.k8sdynamicclient import K8SDynamicClient
+    from ansible_collections.kubernetes.core.plugins.module_utils import k8sdynamicclient
     from ansible_collections.kubernetes.core.plugins.module_utils.client.discovery import LazyDiscoverer
     IMP_K8S_CLIENT = True
 except ImportError as e:
@@ -195,7 +195,7 @@ def auth_set(*names):
         return client
 
     try:
-        client = K8SDynamicClient(kubernetes.client.ApiClient(configuration), discoverer=LazyDiscoverer)
+        client = k8sdynamicclient.K8SDynamicClient(kubernetes.client.ApiClient(configuration), discoverer=LazyDiscoverer)
     except Exception as err:
         _raise_or_fail(err, 'Failed to get client due to %s')
 
